before_install:
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install -g cleverstack-cli

before_script:
  - export NODE_ENV=test
  - export NODE_PATH=./lib/:./modules/

script:
  - "npm test"

notifications:
  email:
    - cleverstack@github.com
  irc:
    - "chat.freenode.net#cleverstack"

env:
  - NODE_ENV=test; NODE_PATH=./lib/:./modules/

language: node_js

node_js:
  - '0.10'
  - '0.11'
  - '0.12'
  - 'iojs'

branches:
  only:
    - master

cache:
  directories:
    - node_modules
